description = "UBI 10 Buildpackless Builder with no buildpacks included. To use, specify buildpacks at build time."

[build]
  image = "docker.io/paketobuildpacks/ubi-10-build-base:0.0.8"

[lifecycle]
  version = "0.21.1"

[run]

  [[run.images]]
    image = "docker.io/paketobuildpacks/ubi-10-run-base:latest"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"

[[targets]]
  arch = "ppc64le"
  os = "linux"

[[targets]]
  arch = "ppc64le"
  os = "linux"

[[targets]]
  arch = "s390x"
  os = "linux"
